language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer install --no-interaction
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2 libxml2-dev
  
script: 
  - php -i
  - vendor/bin/phpunit --coverage-text
